### ISSUE TITLE
parentsId null for all commits

### ISSUE THREAD

**Issue by blizzard384** [timols/java-gitlab-api#165] opened 2016-10-07 14:42 UTC
When getting commits via method getAllCommits(projectId, branchName), every commit has parentsId null. I believe this is a bug.

**Comment by BenLevine** [comment] 2017-02-17 14:54
Pretty sure that the issue with this is that the REST call that getAllCommits method makes does not return back parentId as part of the response dataset. From the GitLab API docs, it looks like ParentId only comes back when you query a specific commit. A richer set of data comes back with the single commit request than what comes back from a get all commits on a project.

**Comment by BenLevine** [comment] 2017-02-17 14:55
Pretty sure that the issue with this is that the REST call that getAllCommits method makes does not return back parentId as part of the response dataset. From the GitLab API docs, it looks like ParentId only comes back when you query a specific commit. A richer set of data comes back with the single commit request than what comes back from a get all commits on a project.

**Comment by StLBen** [comment] 2017-02-17 19:41
I confirmed this behavior is accurate. Parent Ids are only present in the JSON from the GitLab API when pulling an individual commit and not when pulling the full list of commits for the project. There are two ways to handle. One way would be to handle on the implementer end and loop through your list of commits to get the individual commit and update the missing data. The other way would be to write an additional method into the java-gitlab-api that can be called that does this process and returns the full data set. Second option seems more complete. 

For the record, it appears that authored_date, committed_date, stats, and status all have this behavior in that they only come back from the direct commit pull. Currently, this api doesn't support stats or status and also is missing committer_name and committer_email.

**Closed** 2017-04-16 20:27 UTC
